#!/bin/bash
# A shell script to download random images from https://iw233.cn/API/Random.php
# Usage: ./image_down <folder> <number>

set -ux

# Check if the folder and number arguments are provided
if [ $# -ne 2 ]; then
  echo "Usage: ./image_down <folder> <number>"
  exit 1
fi

sleep 5s

# Assign the arguments to variables
folder=$1
number=$2

# Check if the folder exists, if not create it
if [ ! -d "$folder" ]; then
  mkdir -p -v "$folder"
  mkdir -p -v "$folder"/yin
  mkdir -p -v "$folder"/cat
  mkdir -p -v "$folder"/pc
fi

# Loop for the number of times specified by the user
for ((i=1; i<=$number; i++))
do
  # Generate a random file name with jpg extension
  filename=$(date +%s%N).jpg

  # Download the image from the url and save it to the folder with the file name
  curl -sL https://iw233.cn/api.php?sort=yin -o "$folder/yin/$filename"
  curl -sL https://iw233.cn/api.php?sort=cat -o "$folder/cat/$filename"
  curl -sL https://iw233.cn/api.php?sort=pc -o "$folder/pc/$filename"
  # Print a message to show the progress
  echo "Downloaded image $i of $number"
done

# Print a message to show the completion
echo "Done. Downloaded $number images to $folder."
