name: Upload Images 
  
on:
   push: 
     branches: [ main ] 
   schedule: 
     - cron: "30 12 * * *" 
   workflow_dispatch: 
  
permissions: 
   contents: write 
  
jobs: 
   build: 
     runs-on: ubuntu-latest 
  
     steps: 
     # Check out repository under $GITHUB_WORKSPACE, so the job can access it 
     - name: Checkout Repo
       uses: actions/checkout@v3

     - name: Pull Repo
       run: |
         git clone https://github.com/dpkg123/image_down code
     - name: Download Image
       run: |
         cd code
         sudo chmod 777 -v image_down
         ./image_down image-`(date +%Y-%m-%d)` 1000
         cd ..

     - name: Delete Images
       run: |
          cd code
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +10M -print
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +10M -delete
          cd ..
          
     - name: Commit and Push
       run: |
          cd code
          git config --local user.name "GitHub Actions" 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm -rf image_down LICENSE .github -v
          git checkout -b image-`(date +%Y-%m-%d)`
          git add .
          git commit -m "image-upload:$(date)"
          git push -u origin +image-`(date +%Y-%m-%d)`
       env: 
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
