name: Upload Images 
  
on:
   push: 
     branches: [ main ] 
   schedule: 
     - cron: "30 12 * * *" 
   workflow_dispatch: 
  
permissions: 
   contents: write 
  
jobs: 
   build: 
     runs-on: ubuntu-latest 
  
     steps: 
     # Check out repository under $GITHUB_WORKSPACE, so the job can access it 
     - name: Checkout Repo
       uses: actions/checkout@v3

     - name: Pull Repo
       run: |
         git clone https://github.com/dpkg123/image_down -b main code
         
     - name: Download Image
       run: |
         cd code
         sudo chmod 777 -v image_down
         ./image_down image-`(date +%Y-%m-%d)` 350
         cd ..

     - name: Delete Images
       run: |
          cd code
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size -2M -print
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size -2M -delete
          cd ..
          
     - name: Delete Images Stage2
       run: |
          cd code
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +10M -print
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +10M -delete
          cd ..

     - name: Configure actions-user
       run: |
         cd code
         git config --global user.name "GitHub Action"
         git config --global user.email "actions@github.com"
         cd ..

     - name: Commit Changes
       run: |
          cd code
          rm -rf LICENSE .github -v
          git checkout -b img
          git add .
          git commit -m "image-upload:$(date)"
          
     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
        github_token: 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
        branch: img
      
