name: Upload Images 
  
on:
   push: 
     branches: [ main ] 
   schedule: 
     - cron: "30 12 1,11,21,28 * *" 
   workflow_dispatch: 
  
permissions: 
   contents: write 
  
jobs: 
   build: 
     runs-on: ubuntu-latest 
  
     steps: 
     # Check out repository under $GITHUB_WORKSPACE, so the job can access it 
     - name: Checkout Repo
       uses: actions/checkout@v4
 
     - name: Download Image
       run: |
         sudo chmod 777 -v image_down
         ./image_down image-`(date +%Y-%m-%d)` 1000

     - name: Delete Images
       run: |
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size -4M -print
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size -4M -delete
          
     - name: Delete Images Stage2
       run: |
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +8M -print
          sudo find . -type f \( -name "*.jpeg" -o -name "*.png" -o -name "*.jpg" \) -size +8M -delete
          
     - name: Upload to Artifact
       uses: actions/upload-artifact@v3
       with: 
        name: "image"
        path: image*



   build-1: 
     runs-on: ubuntu-latest 
  
     steps: 
     # Check out repository under $GITHUB_WORKSPACE, so the job can access it 
     - name: Checkout Repo
       run: git clone https://github.com/dabao1955/MirlKoi-Image code
     - run: make -C code -n -j8 
