name: Upload Images 
  
on:
   push: 
     branches: [ main ] 
   schedule: 
     - cron: "0 12 1,11,21,28 * *" 
   workflow_dispatch: 
  
permissions: 
   contents: write 
  
jobs: 
   build: 
     runs-on: ubuntu-latest 
  
     steps: 
     # Check out repository under $GITHUB_WORKSPACE, so the job can access it 
     - name: Checkout Repo
       uses: actions/checkout@v4
 
     - name: Download Image
       run: |
         sudo chmod 777 image_down
         sed -i 's/set -e/set -ex/g' image_down
         ./image_down image-`(date +%Y-%m-%d)` 50

     - name: Delete Images
       run: |
           cp delete_image $number 
           cd $number
           sed -i 's/set -e/set -ex/g' image_down
           bash delete_image 4 8
           
     - name: Upload to Artifact
       if: github.event_name == 'schedule'
       uses: actions/upload-artifact@v4
       with: 
        name: "image"
        path: image*
        retention-days: 21
